### ISSUE TITLE
安装过程中flask deploy 失败

### ISSUE THREAD

**Issue by shuish0071** [qunarcorp/open_dnsdb#1]
各位好：

   在部署到【flask deploy】出现报错无法打开文件，我试着安装sqlite3，但是也无法解决，希望能得到一些帮助。

环境：centos 7.5 python2.7

报错日志如下：
(.venv) [root@localhost open_dnsdb]# flask deploy
2019-01-23 10:57:49.437 14027 CRITICAL dnsdb [-] (sqlite3.OperationalError) unable to open database file
2019-01-23 10:57:49.437 14027 TRACE dnsdb Traceback (most recent call last):
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/bin/flask", line 10, in <module>
2019-01-23 10:57:49.437 14027 TRACE dnsdb     sys.exit(main())
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/flask/cli.py", line 894, in main
2019-01-23 10:57:49.437 14027 TRACE dnsdb     cli.main(args=args, prog_name=name)
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/flask/cli.py", line 557, in main
2019-01-23 10:57:49.437 14027 TRACE dnsdb     return super(FlaskGroup, self).main(*args, **kwargs)
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/click/core.py", line 717, in main
2019-01-23 10:57:49.437 14027 TRACE dnsdb     rv = self.invoke(ctx)
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
2019-01-23 10:57:49.437 14027 TRACE dnsdb     return _process_result(sub_ctx.command.invoke(sub_ctx))
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/click/core.py", line 956, in invoke
2019-01-23 10:57:49.437 14027 TRACE dnsdb     return ctx.invoke(self.callback, **ctx.params)
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/click/core.py", line 555, in invoke
2019-01-23 10:57:49.437 14027 TRACE dnsdb     return callback(*args, **kwargs)
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
2019-01-23 10:57:49.437 14027 TRACE dnsdb     return f(get_current_context(), *args, **kwargs)
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/flask/cli.py", line 412, in decorator
2019-01-23 10:57:49.437 14027 TRACE dnsdb     return __ctx.invoke(f, *args, **kwargs)
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/click/core.py", line 555, in invoke
2019-01-23 10:57:49.437 14027 TRACE dnsdb     return callback(*args, **kwargs)
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/dnsdb_command.py", line 157, in deploy
2019-01-23 10:57:49.437 14027 TRACE dnsdb     db.create_all()
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 963, in create_all
2019-01-23 10:57:49.437 14027 TRACE dnsdb     self._execute_for_all_tables(app, bind, 'create_all')
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 955, in _execute_for_all_tables
2019-01-23 10:57:49.437 14027 TRACE dnsdb     op(bind=self.get_engine(app, bind), **extra)
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 3695, in create_all
2019-01-23 10:57:49.437 14027 TRACE dnsdb     tables=tables)
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1855, in _run_visitor
2019-01-23 10:57:49.437 14027 TRACE dnsdb     with self._optional_conn_ctx_manager(connection) as conn:
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
2019-01-23 10:57:49.437 14027 TRACE dnsdb     return self.gen.next()
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1848, in _optional_conn_ctx_manager
2019-01-23 10:57:49.437 14027 TRACE dnsdb     with self.contextual_connect() as conn:
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2039, in contextual_connect
2019-01-23 10:57:49.437 14027 TRACE dnsdb     self._wrap_pool_connect(self.pool.connect, None),
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect
2019-01-23 10:57:49.437 14027 TRACE dnsdb     e, dialect, self)
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection
2019-01-23 10:57:49.437 14027 TRACE dnsdb     exc_info
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
2019-01-23 10:57:49.437 14027 TRACE dnsdb     reraise(type(exception), exception, tb=exc_tb, cause=cause)
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
2019-01-23 10:57:49.437 14027 TRACE dnsdb     return fn()
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 376, in connect
2019-01-23 10:57:49.437 14027 TRACE dnsdb     return _ConnectionFairy._checkout(self)
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 713, in _checkout
2019-01-23 10:57:49.437 14027 TRACE dnsdb     fairy = _ConnectionRecord.checkout(pool)
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 480, in checkout
2019-01-23 10:57:49.437 14027 TRACE dnsdb     rec = pool._do_get()
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1151, in _do_get
2019-01-23 10:57:49.437 14027 TRACE dnsdb     return self._create_connection()
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 323, in _create_connection
2019-01-23 10:57:49.437 14027 TRACE dnsdb     return _ConnectionRecord(self)
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 449, in __init__
2019-01-23 10:57:49.437 14027 TRACE dnsdb     self.connection = self.__connect()
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 607, in __connect
2019-01-23 10:57:49.437 14027 TRACE dnsdb     connection = self.__pool._invoke_creator(self)
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 97, in connect
2019-01-23 10:57:49.437 14027 TRACE dnsdb     return dialect.connect(*cargs, **cparams)
2019-01-23 10:57:49.437 14027 TRACE dnsdb   File "/opt/open_dnsdb/.venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 385, in connect
2019-01-23 10:57:49.437 14027 TRACE dnsdb     return self.dbapi.connect(*cargs, **cparams)
2019-01-23 10:57:49.437 14027 TRACE dnsdb OperationalError: (sqlite3.OperationalError) unable to open database file
2019-01-23 10:57:49.437 14027 TRACE dnsdb

**Comment by shiweijie** [comment]
没有这个目录吧 open_dnsdb ，我也遇到了，貌似有两个目录 open_dnsdb  open-dnsdb

**Comment by shuish0071** [comment]
> 没有这个目录吧 open_dnsdb ，我也遇到了，貌似有两个目录 open_dnsdb open-dnsdb

哥们，我存放的目录为/opt/open_dnsdb，你指的是/opt/open_dnsdb  下面还有个/opt/open_dnsdb/open-dnsdb，是这个意思吗？

**Comment by shuish0071** [comment]
(.venv) [root@localhost open_dnsdb]# pwd
/opt/open_dnsdb
(.venv) [root@localhost open_dnsdb]# ll
total 56
drwxr-xr-x 6 root root   211 Jan 23 09:44 dnsdb
-rw-r--r-- 1 root root 10380 Jan 22 18:08 dnsdb_command.py
-rw-r--r-- 1 root root 10303 Jan 23 09:44 dnsdb_command.pyc
drwxr-xr-x 4 root root    71 Jan 23 09:44 dnsdb_common
drwxr-xr-x 6 root root   239 Jan 22 18:08 dnsdb_fe
drwxr-xr-x 6 root root   130 Jan 22 18:08 dns_updater
drwxr-xr-x 2 root root    70 Jan 22 18:08 docs
drwxr-xr-x 4 root root    34 Jan 22 18:08 etc
-rw-r--r-- 1 root root 11357 Jan 22 18:08 LICENSE
drwxr-xr-x 3 root root   106 Jan 23 11:27 migrations
-rw-r--r-- 1 root root  2550 Jan 22 18:08 README.md
-rw-r--r-- 1 root root   309 Jan 22 18:08 requirements.txt
-rw-r--r-- 1 root root   641 Jan 22 18:08 setup.cfg
-rw-r--r-- 1 root root   180 Jan 22 18:08 setup.py
-rw-r--r-- 1 root root    35 Jan 22 18:08 test-requirements.txt
drwxr-xr-x 2 root root     6 Jan 23 09:44 tmp
drwxr-xr-x 3 root root   144 Jan 23 10:19 tools

**Comment by LostSymbol** [comment]
需要先新建数据库文件, 配置在文件 etc/beta/common.conf: 
`[DB]
connection=sqlite:////usr/local/open_dnsdb/dnsdb.db`

新建命令：
`mkdir -p /usr/local/open_dnsdb && touch /usr/local/open_dnsdb/dnsdb.db
`
根据自己情况修改即可

**Comment by shuish0071** [comment]
> 需要先新建数据库文件, 配置在文件 etc/beta/common.conf:
> `[DB] connection=sqlite:////usr/local/open_dnsdb/dnsdb.db`
> 
> 新建命令：
> `mkdir -p /usr/local/open_dnsdb && touch /usr/local/open_dnsdb/dnsdb.db `
> 根据自己情况修改即可

你好，目前我已经部署完毕，但是登陆账号密码默认是多少？

**Comment by LostSymbol** [comment]
> 你好，目前我已经部署完毕，但是登陆账号密码默认是多少？

123456

**Comment by shuish0071** [comment]
> > 你好，目前我已经部署完毕，但是登陆账号密码默认是多少？
> 
> 123456

账号呢？我试过 root 、admin、dnsdb、123456 、opendnsdb、open_dnsdb。。。。我都蒙不下去了

**Comment by shuish0071** [comment]
> > > 你好，目前我已经部署完毕，但是登陆账号密码默认是多少？
> > 
> > 
> > 123456
> 
> 账号呢？我试过 root 、admin、dnsdb、123456 、opendnsdb、open_dnsdb。。。。我都蒙不下去了

好吧，查查数据库 test，强行来一波sqlite3

**Comment by shuish0071** [comment]
> > 你好，目前我已经部署完毕，但是登陆账号密码默认是多少？
> 
> 123456

**Comment by shiweijie** [comment]
> > > 你好，目前我已经部署完毕，但是登陆账号密码默认是多少？
> > 
> > 
> > 123456

test / 123456

**Comment by shuish0071** [comment]
关了，感谢回复
