### ISSUE TITLE
open-dnsdb-conf/zone-updater启动失败

### ISSUE THREAD

**Issue by wanglong19940907** [qunarcorp/open_dnsdb#11]
**问题描述**
1、按https://github.com/qunarcorp/open_dnsdb/wiki/startUpdater文档进行部署完，supervisord中 reload时候,dns-dnsdb-conf-updater和dns-dns-zone-updater均启动不正常，错误提示如下：

![qq 20190307104722](https://user-images.githubusercontent.com/48304198/53928927-ef0fc080-40c6-11e9-8087-ae23bf499f67.png)

(.venv) [root@localhost named]# /usr/local/open_dnsdb/tools/with_venv.sh dnsdb-conf-updater beta dnsdb-updater
2019-03-07 10:46:25.694 8708 CRITICAL dnsdb_updater_www [-] DnsdbApi调用失败: {"message": "\u8bf7\u5148\u5c06ip 192.168.11.67 \u5199\u5165\u6570\u636e\u5e93", "data": null, "errcode": 400, "msg_en": "No such ip record: 192.168.11.67"}
2019-03-07 10:46:25.694 8708 TRACE dnsdb_updater_www Traceback (most recent call last):
2019-03-07 10:46:25.694 8708 TRACE dnsdb_updater_www   File "/usr/local/open_dnsdb/.venv/bin/dnsdb-conf-updater", line 6, in <module>
2019-03-07 10:46:25.694 8708 TRACE dnsdb_updater_www     from dns_updater.app import app_start
2019-03-07 10:46:25.694 8708 TRACE dnsdb_updater_www   File "/usr/local/open_dnsdb/dns_updater/app.py", line 45, in <module>
2019-03-07 10:46:25.694 8708 TRACE dnsdb_updater_www     application = create_app()
2019-03-07 10:46:25.694 8708 TRACE dnsdb_updater_www   File "/usr/local/open_dnsdb/dns_updater/app.py", line 21, in create_app
2019-03-07 10:46:25.694 8708 TRACE dnsdb_updater_www     setup_config(sys.argv[1], 'dnsdb-updater', conf_dir=os.path.dirname(os.path.dirname(__file__)))
2019-03-07 10:46:25.694 8708 TRACE dnsdb_updater_www   File "/usr/local/open_dnsdb/dns_updater/config.py", line 139, in setup_config
2019-03-07 10:46:25.694 8708 TRACE dnsdb_updater_www     CONF.host_group = DnsdbApi.get_host_group()['data']
2019-03-07 10:46:25.694 8708 TRACE dnsdb_updater_www   File "/usr/local/open_dnsdb/dns_updater/utils/updater_util.py", line 78, in get_host_group
2019-03-07 10:46:25.694 8708 TRACE dnsdb_updater_www     data={"host_ip": get_self_ip()})
2019-03-07 10:46:25.694 8708 TRACE dnsdb_updater_www   File "/usr/local/open_dnsdb/dnsdb_common/library/api.py", line 64, in get_form
2019-03-07 10:46:25.694 8708 TRACE dnsdb_updater_www     return self._get(url, *args, **dict(kwargs, **{'ctype': 'form'}))
2019-03-07 10:46:25.694 8708 TRACE dnsdb_updater_www   File "/usr/local/open_dnsdb/dnsdb_common/library/api.py", line 45, in _get
2019-03-07 10:46:25.694 8708 TRACE dnsdb_updater_www     return self.resp_wrapper(resp, req)
2019-03-07 10:46:25.694 8708 TRACE dnsdb_updater_www   File "/usr/local/open_dnsdb/dns_updater/utils/updater_util.py", line 64, in _dnsdb_resp_wrapper
2019-03-07 10:46:25.694 8708 TRACE dnsdb_updater_www     raise UpdaterErr(u'DnsdbApi调用失败: %s' % json.dumps(resp), 400, json.dumps(resp))
2019-03-07 10:46:25.694 8708 TRACE dnsdb_updater_www UpdaterErr: DnsdbApi调用失败: {"message": "\u8bf7\u5148\u5c06ip 192.168.11.67 \u5199\u5165\u6570\u636e\u5e93", "data": null, "errcode": 400, "msg_en": "No such ip record: 192.168.11.67"}
2019-03-07 10:46:25.694 8708 TRACE dnsdb_updater_www 

2、编辑添加主机时提示：

![qq 20190307105458](https://user-images.githubusercontent.com/48304198/53929101-92f96c00-40c7-11e9-9e77-51ba3425d052.png)

3、编辑配置文件时提示：

![qq 20190307105642](https://user-images.githubusercontent.com/48304198/53929148-b91f0c00-40c7-11e9-965c-ebe7d5e5fae4.png)

**环境配置**
环境配置均与文档描述一致

**复现步骤**
1.
2.
3.

**实际输出结果**

**期望输出结果**

**Comment by wanglong19940907** [comment]
希望大佬可以指点迷津，不胜感激

**Comment by wanglong19940907** [comment]
![image](https://user-images.githubusercontent.com/48304198/53929979-9e9a6200-40ca-11e9-8e99-666de291face.png)
这是启动bind时的提示

**Comment by LostSymbol** [comment]
updater启用成功的前提是其主机在dnsdb中有记录，就是说你添加主机没有成功

‘not enough level’ 主机名太过简单了,需要至少是 'local.test' 这样，错误提示后续改进

**Comment by wanglong19940907** [comment]
非常感谢作者在百忙之中回复本人，经作者的提示已经成功添加主机，可updater任然不能启动，是否是因为bind未能成功启动的缘故呢？  作者说是因为master主机组没有添加进dnsdb中，我查看后发现dnsdb中是有的

sqlite> select * from tb_dns_host_group;
2019-03-06 17:35:52.282515|2019-03-07 11:00:37.106954|1|Master|master||1

![qq 20190308092023](https://user-images.githubusercontent.com/48304198/54000729-83d7f400-4183-11e9-8a93-eeef53e63e38.png)

**Comment by wanglong19940907** [comment]
![qq 20190308092445](https://user-images.githubusercontent.com/48304198/54000901-390aac00-4184-11e9-9b9f-7ed7809c8611.png)

**Comment by LostSymbol** [comment]
updater无法启动的错误日志发一下，请确认主机ip是一样的，看你之前贴的错误日志‘No such ip record: 192.168.11.67’ 跟dnsdb中的不一样啊

ps: dnsdb系统本身不关注bind的状态，为了让域名、配置同步生效 named-checkconf named-checkzone rndc mkrdns这几个命令要能用；如果只是为了测试可以把 etc/beta/common.conf 中的 env 参数改为'dev'

**Comment by wanglong19940907** [comment]
感谢作者的提示，open-dnsdb-conf-updater 已正常启动， 可是open-dnsdb-zone-updater却依然无法启动，看了错误提示，可目录明明正确存在
2019-03-08 18:17:58.201 10684 ERROR dns_updater.updater [-] Host belong to group: Master
2019-03-08 18:17:58.202 10684 ERROR dns_updater.updater [-] No such directory: /usr/local/open-dnsdb/tmp
![qq 20190308182147](https://user-images.githubusercontent.com/48304198/54023115-0fc33d80-41cf-11e9-9f3e-0559baccae6a.png)

2019-03-08 18:17:58.202 10684 TRACE dns_updater.updater Traceback (most recent call last):
2019-03-08 18:17:58.202 10684 TRACE dns_updater.updater   File "/usr/local/open_dnsdb/dns_updater/updater.py", line 92, in init_app
2019-03-08 18:17:58.202 10684 TRACE dns_updater.updater     _check_necessary_options()
2019-03-08 18:17:58.202 10684 TRACE dns_updater.updater   File "/usr/local/open_dnsdb/dns_updater/updater.py", line 73, in _check_necessary_options
2019-03-08 18:17:58.202 10684 TRACE dns_updater.updater     raise UpdaterErr(message='No such directory: %s' % dir_path)
2019-03-08 18:17:58.202 10684 TRACE dns_updater.updater UpdaterErr: No such directory: /usr/local/open-dnsdb/tmp
2019-03-08 18:17:58.202 10684 TRACE dns_updater.updater 
![qq 20190308180937](https://user-images.githubusercontent.com/48304198/54022952-a3e0d500-41ce-11e9-8b72-5f8d24093a2b.png)
![qq 20190308181414](https://user-images.githubusercontent.com/48304198/54022956-a6432f00-41ce-11e9-9f38-cd8b1fca9a83.png)

**Comment by wanglong19940907** [comment]
非常感谢作者的指点，问题已解决。谢谢~

**Comment by wanglong19940907** [comment]
再请教一下作者，web界面这操作日志板块，提示异常状态码undefined，是哪里需要改呢？ 有点懵~~

![QQ图片20190311100151](https://user-images.githubusercontent.com/48304198/54096220-eb8d7980-43e5-11e9-8309-aa4db2c74c46.png)

**Comment by LostSymbol** [comment]
这个不好说 
`supervisorctl -c /etc/supervisord.conf`
`tail -f open-dnsdb`
重新请求下页面，看下错误

**Comment by wanglong19940907** [comment]
好像没有看到什么错误哦
[2019-03-11 14:36:16 +0000] [13762] [DEBUG] GET /api/get/update_zones
[2019-03-11 14:36:16 +0000] [13762] [DEBUG] Closing connection. 
[2019-03-11 14:36:17 +0000] [13763] [DEBUG] GET /web/preview/list/operation_log
[2019-03-11 14:36:17 +0000] [13761] [DEBUG] GET /web/preview/list/operation_constant
[2019-03-11 14:36:21 +0000] [13767] [DEBUG] GET /api/get/update_zones
[2019-03-11 14:36:21 +0000] [13767] [DEBUG] Closing connection. 

![QQ图片20190311143727](https://user-images.githubusercontent.com/48304198/54104570-5b622b00-440b-11e9-846f-e06d35bf7d1f.png)

**Comment by LostSymbol** [comment]
浏览器的前端调试工具会用么，看一下`/web/preview/list/operation_log`这条请求的返回
![image](https://user-images.githubusercontent.com/24261160/54111367-a8033180-441e-11e9-8654-9094f846f0cc.png)

response里的内容：
![image](https://user-images.githubusercontent.com/24261160/54111480-e698ec00-441e-11e9-8dac-4f8e7bff0398.png)

没什么异常的话，简单粗暴一点， 给我看下`tb_operation_log`这张表里的内容

**Comment by wanglong19940907** [comment]
感谢作者恢复，用火狐浏览器是正常的，其他的比如360，搜狗浏览器都不行，顺便问下，主机管理→编辑配置保存后， 主机的配置md5值怎么和主机组的md5同步一直处于等待状态呢？

![QQ图片20190311172120](https://user-images.githubusercontent.com/48304198/54112907-27decb00-4422-11e9-81a5-3f8662aa362b.png)

![QQ图片20190311171732](https://user-images.githubusercontent.com/48304198/54112899-244b4400-4422-11e9-922e-50b0aca1e7c5.png)

**Comment by wanglong19940907** [comment]
open_dnsdb 一直在输出这个

![QQ图片20190311172948](https://user-images.githubusercontent.com/48304198/54113514-6b860480-4423-11e9-8b7b-9679bc97f814.png)

**Comment by LostSymbol** [comment]
dns zone的同步是通过线程不断检测实现的，一直有‘GET /api/get/update_zones’是正常的

处于等待问题这个，我这儿没有复现出来，能否看看有没有异常日志呢

**Comment by wanglong19940907** [comment]
open-dnsdb 日志报这个错：
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/local/open_dnsdb/dnsdb/deploy.py", line 104, in run
    raise DeployException('No deploy job id=%s or job state=wait.' % self.job_id)
DeployException: No deploy job id=27 or job state=wait.

![QQ图片20190311181144](https://user-images.githubusercontent.com/48304198/54116201-367cb080-4429-11e9-823f-5a627e6f8192.png)

**Comment by LostSymbol** [comment]
多谢，我研究下～

**Comment by LostSymbol** [comment]
代码已更新，麻烦更新下再试试

**Comment by wanglong19940907** [comment]
更新后，正常了，谢谢作者

**Comment by wanglong19940907** [comment]
请问下，添加zone时报这个错是什么原因呢？
![QQ图片20190318143451](https://user-images.githubusercontent.com/48304198/54511202-29ad0f00-498b-11e9-84fe-0fa11e0e3146.png)

**Comment by LostSymbol** [comment]
有没有错误日志看一下

**Comment by wanglong19940907** [comment]
[2019-04-01 16:37:53 +0000] [15302] [DEBUG] GET /api/get/update_zones
[2019-04-01 16:37:53 +0000] [15302] [DEBUG] Closing connection. 
[2019-04-01 16:37:57 +0000] [15307] [DEBUG] POST /web/config/add/named_zone
2019-04-01 16:37:57.244 15307 ERROR dnsdb_common.library.decorators [-] func: add_named_zone, args: (), kwargs: {'zone_type': 2, 'add_header': True, 'username': u'test', 'conf': {u'Master': u'zone "test.master" {\n\ttype master;\n\tfile "test.master";\n};'}, 'zone': 'test.master'}
2019-04-01 16:37:57.245 15307 ERROR dnsdb_common.library.decorators [-] [Errno 2] No such file or directory: '../etc/template/zone_header'
2019-04-01 16:37:57.245 15307 TRACE dnsdb_common.library.decorators Traceback (most recent call last):
2019-04-01 16:37:57.245 15307 TRACE dnsdb_common.library.decorators   File "/usr/local/open_dnsdb/dnsdb_common/library/decorators.py", line 89, in decorator
2019-04-01 16:37:57.245 15307 TRACE dnsdb_common.library.decorators     return resp(data=func(*kargs, **kwargs), is_json=is_json)
2019-04-01 16:37:57.245 15307 TRACE dnsdb_common.library.decorators   File "/usr/local/open_dnsdb/dnsdb_common/library/decorators.py", line 188, in _wrapper
2019-04-01 16:37:57.245 15307 TRACE dnsdb_common.library.decorators     ret = func(*args, **kwargs)
2019-04-01 16:37:57.245 15307 TRACE dnsdb_common.library.decorators   File "/usr/local/open_dnsdb/dnsdb/view/web/config.py", line 188, in add_named_zone
2019-04-01 16:37:57.245 15307 TRACE dnsdb_common.library.decorators     return HostGroupConfDal.add_named_zone(zone, zone_type, conf, add_header, username)
2019-04-01 16:37:57.245 15307 TRACE dnsdb_common.library.decorators   File "/usr/local/open_dnsdb/dnsdb_common/dal/host_group_conf.py", line 267, in add_named_zone
2019-04-01 16:37:57.245 15307 TRACE dnsdb_common.library.decorators     with open(file_name) as f:
2019-04-01 16:37:57.245 15307 TRACE dnsdb_common.library.decorators IOError: [Errno 2] No such file or directory: '../etc/template/zone_header'
2019-04-01 16:37:57.245 15307 TRACE dnsdb_common.library.decorators 

![QQ图片20190401163835](https://user-images.githubusercontent.com/48304198/55314478-d1066780-549c-11e9-94ce-a0d74aec97a3.png)

**Comment by wanglong19940907** [comment]
日志提示说我没有模板文件zone_header.可我是有的

![QQ图片20190401164141](https://user-images.githubusercontent.com/48304198/55314684-3ce8d000-549d-11e9-8a71-bd73090ccab3.png)

**Comment by wanglong19940907** [comment]
日志错误提示说我没有zone_header，可这里明明有的

![QQ图片20190401164141](https://user-images.githubusercontent.com/48304198/55314763-6dc90500-549d-11e9-9b88-631d32df081b.png)

**Comment by LostSymbol** [comment]
你的程序是通过命令行直接启动的吧，测了下这种情况下的确会有这个问题，暂时修复: 修改文件`dnsdb_common/dal/host_group_conf.py`中的`file_name = '../etc/template/zone_header'`，换成绝对路径应该可以解决问题。后续我会把这个放到配置文件里

**Comment by wanglong19940907** [comment]
问题解决了，然后我添加了域名的解析记录，可我测试的时候怎么ping不通呢？

![QQ图片20190404153458](https://user-images.githubusercontent.com/48304198/55537802-93e5e380-56ef-11e9-89d0-9d07b10bd03b.png)

![QQ图片20190404153856](https://user-images.githubusercontent.com/48304198/55537908-c7c10900-56ef-11e9-81e8-7438748a5e98.png)

**Comment by LostSymbol** [comment]
看起来域名解析没有生效啊
1、首先确定你的bind服务正常
2、设置你的`/etc/resolv.conf`: `nameserver bind.ip`, 
3、用dig命令测试域名是否生效
4、域名没有生效的话看下zone文件记录有没有更新成功（通过dnsdb-zone-updater服务更新的）
bind相关可以看下 http://cn.linux.vbird.org/linux_server/0350dns_4.php

**Comment by wss434631143** [comment]
我的也是解析没生效：
看起来域名解析没有生效啊
[1、首先确定你的bind服务正常](url)
2、设置你的/etc/resolv.conf: nameserver bind.ip,
3、用dig命令测试域名是否生效
4、域名没有生效的话看下zone文件记录有没有更新成功（通过dnsdb-zone-updater服务更新的）
bind相关可以看下 http://cn.linux.vbird.org/linux_server/0350dns_4.php

第4条检查了，/usr/local/open_dnsdb/tmp/var/named/下的配置文件更新了，但是/var/named/下的配置文件没更新。
<img width="507" alt="微信截图_20190407223916" src="https://user-images.githubusercontent.com/6138576/55685235-46cf6f00-5986-11e9-98cf-7857b38fe8ec.png">

**Comment by LostSymbol** [comment]
> 我的也是解析没生效：
> 第4条检查了，/usr/local/open_dnsdb/tmp/var/named/下的配置文件更新了，但是/var/named/下的配置文件没更新。

看下dnsdb-zone-updater程序的日志应该有报错

**Comment by diboca** [comment]
有什么进展吗？我也遇到了这个问题，解析不生效。/usr/local/open_dnsdb/tmp/var/named/下的配置文件更新了，但是/var/named/下的配置文件没更新。

**Comment by zhouze2544** [comment]
1./usr/local/open_dnsdb/tmp**/var/named/** 需要手动创建
基于以上创建zone的时候 在/usr/local/open_dnsdb/tmp/var/named/ 创建相应的zone（test），然后同步到报错，相关报错named-checkzone.log，报错如下：

dns_master_load: /usr/local/open_dnsdb/tmp/var/named/test:10: extra input text
/usr/local/open_dnsdb/tmp/var/named/test: file does not end with newline
zone test/IN: loading from master file /usr/local/open_dnsdb/tmp/var/named/test failed: extra input text
zone test/IN: not loaded due to errors.

![image](https://user-images.githubusercontent.com/25238167/69009631-2e9ae600-0992-11ea-8c77-4b365b2bd5e4.png)
