### ISSUE TITLE
open-dnsdb启动成功，open-dnsdb-conf-updater启动报错

### ISSUE THREAD

**Issue by wss434631143** [qunarcorp/open_dnsdb#18]
**问题描述**
open-dnsdb启动成功，主机组已添加，并在数据库中查询到，open-dnsdb-conf-updater启动报错,

**环境配置**
Centos 7.2
Python 3.6.8

**报错日志**
HTTPConnectionPool(host='localhost', port=9001): Max retries exceeded with url: /api/get/host_group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f85468b5518>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-04-07 18:29:47.724 2944 TRACE dnsdb_updater_www Traceback (most recent call last):
2019-04-07 18:29:47.724 2944 TRACE dnsdb_updater_www   File "/usr/local/open_dnsdb/.venv/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
2019-04-07 18:29:47.724 2944 TRACE dnsdb_updater_www     (self._dns_host, self.port), self.timeout, **extra_kw)
2019-04-07 18:29:47.724 2944 TRACE dnsdb_updater_www   File "/usr/local/open_dnsdb/.venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
2019-04-07 18:29:47.724 2944 TRACE dnsdb_updater_www     raise err
2019-04-07 18:29:47.724 2944 TRACE dnsdb_updater_www   File "/usr/local/open_dnsdb/.venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
2019-04-07 18:29:47.724 2944 TRACE dnsdb_updater_www     sock.connect(sa)
2019-04-07 18:29:47.724 2944 TRACE dnsdb_updater_www ConnectionRefusedError: [Errno 111] Connection refused
2019-04-07 18:29:47.724 2944 TRACE dnsdb_updater_www 
2019-04-07 18:29:47.724 2944 TRACE dnsdb_updater_www During handling of the above exception, another exception occurred:
2019-04-07 18:29:47.724 2944 TRACE dnsdb_updater_www 
2019-04-07 18:29:47.724 2944 TRACE dnsdb_updater_www Traceback (most recent call last):
2019-04-07 18:29:47.724 2944 TRACE dnsdb_updater_www   File "/usr/local/open_dnsdb/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
2019-04-07 18:29:47.724 2944 TRACE dnsdb_updater_www     chunked=chunked)
2019-04-07 18:29:47.724 2944 TRACE dnsdb_updater_www   File "/usr/local/open_dnsdb/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
2019-04-07 18:29:47.724 2944 TRACE dnsdb_updater_www     conn.request(method, url, **httplib_request_kw)
2019-04-07 18:29:47.724 2944 TRACE dnsdb_updater_www   File "/usr/local/lib/python3.6/http/client.py", line 1239, in request

**Comment by LostSymbol** [comment]
确定open-dnsdb是启动状态，并且端口是9001?
用这条命令测下看
`curl http://localhost:9001/healthcheck.html`

**Comment by wss434631143** [comment]
后面加上邮箱相关配置后，就可以启动了。

**Comment by LostSymbol** [comment]
感觉没有必然联系，不过解决了就好
