### ISSUE TITLE
域名参数为空

### ISSUE THREAD

**Issue by tomgreenliu** [qunarcorp/open_dnsdb#29]
**问题描述**
页面添加主机组报错“”

**环境配置**
7.51810
版本
0.2releases
**复现步骤**
1.按照手册增加主机组
2.
3.

**实际输出结果**
[2019-04-27 20:47:10 +0000] [9436] [DEBUG] POST /web/config/add/host_group
2019-04-27 20:47:10.960 9436 ERROR dnsdb_common.library.decorators [-] func: add_host_group, args: (), kwargs: {}
2019-04-27 20:47:10.960 9436 ERROR dnsdb_common.library.decorators [-] None str type:localhost.localdomain.
2019-04-27 20:47:10.960 9436 TRACE dnsdb_common.library.decorators Traceback (most recent call last):
2019-04-27 20:47:10.960 9436 TRACE dnsdb_common.library.decorators   File "/usr/local/open_dnsdb/dnsdb_common/library/decorators.py", line 84, in decorator
2019-04-27 20:47:10.960 9436 TRACE dnsdb_common.library.decorators     return resp(data=func(*kargs, **kwargs), is_json=is_json)
2019-04-27 20:47:10.960 9436 TRACE dnsdb_common.library.decorators   File "/usr/local/open_dnsdb/dnsdb_common/library/decorators.py", line 180, in _wrapper
2019-04-27 20:47:10.960 9436 TRACE dnsdb_common.library.decorators     ret = func(*args, **kwargs)
2019-04-27 20:47:10.960 9436 TRACE dnsdb_common.library.decorators   File "/usr/local/open_dnsdb/dnsdb/view/web/config.py", line 82, in add_host_group
2019-04-27 20:47:10.960 9436 TRACE dnsdb_common.library.decorators     group_name, group_type, hosts = _check_and_format_params(params['group_name'], params['hosts'])
2019-04-27 20:47:10.960 9436 TRACE dnsdb_common.library.decorators   File "/usr/local/open_dnsdb/dnsdb/view/web/config.py", line 70, in _check_and_format_params
2019-04-27 20:47:10.960 9436 TRACE dnsdb_common.library.decorators     HostGroupConfDal.check_host(item['host_name'], item['host_ip'])
2019-04-27 20:47:10.960 9436 TRACE dnsdb_common.library.decorators   File "/usr/local/open_dnsdb/dnsdb_common/dal/host_group_conf.py", line 40, in check_host
2019-04-27 20:47:10.960 9436 TRACE dnsdb_common.library.decorators     is_valid_domain_name(hostname)
2019-04-27 20:47:10.960 9436 TRACE dnsdb_common.library.decorators   File "/usr/local/open_dnsdb/dnsdb_common/library/utils.py", line 53, in is_valid_domain_name
2019-04-27 20:47:10.960 9436 TRACE dnsdb_common.library.decorators     is_valid_domain_name_v2(domain_name)
2019-04-27 20:47:10.960 9436 TRACE dnsdb_common.library.decorators   File "/usr/local/open_dnsdb/dnsdb_common/library/utils.py", line 41, in is_valid_domain_name_v2
2019-04-27 20:47:10.960 9436 TRACE dnsdb_common.library.decorators     raise BadParam("None str type:%s." % domain_name, msg_ch=u'域名参数为空')
2019-04-27 20:47:10.960 9436 TRACE dnsdb_common.library.decorators BadParam: None str type:localhost.localdomain.
2019-04-27 20:47:10.960 9436 TRACE dnsdb_common.library.decorators 

**期望输出结果**

**Comment by LostSymbol** [comment]
python版本是什么

**Comment by tomgreenliu** [comment]
![opendnsdb](https://user-images.githubusercontent.com/49442595/57224719-e0994300-703c-11e9-84fc-d2af181cf34b.png)

**Comment by tomgreenliu** [comment]
更新到python3解决，关闭
