### ISSUE TITLE
dnsdb-conf-updater 执行失败

### ISSUE THREAD

**Issue by shiweijie** [qunarcorp/open_dnsdb#3]
**问题描述**
调用dns api时候出错，请问dns需要增加配置吗  

**实际输出结果**
/usr/local/open-dnsdb/tools/with_venv.sh dnsdb-conf-updater beta dnsdb-updater

2019-01-23 15:08:28.217 16864 CRITICAL dnsdb_updater_www [-] DnsdbApi调用失败: {"message": "\u8bf7\u5148\u5c06ip 192.168.41.51 \u5199\u5165\u6570\u636e\u5e93", "data": null, "errcode": 400, "msg_en": "No such ip record: 192.168.41.51"}
2019-01-23 15:08:28.217 16864 TRACE dnsdb_updater_www Traceback (most recent call last):
2019-01-23 15:08:28.217 16864 TRACE dnsdb_updater_www   File "/usr/local/open-dnsdb/.venv/bin/dnsdb-conf-updater", line 6, in <module>
2019-01-23 15:08:28.217 16864 TRACE dnsdb_updater_www     from dns_updater.app import app_start
2019-01-23 15:08:28.217 16864 TRACE dnsdb_updater_www   File "/usr/local/open-dnsdb/dns_updater/app.py", line 45, in <module>
2019-01-23 15:08:28.217 16864 TRACE dnsdb_updater_www     application = create_app()
2019-01-23 15:08:28.217 16864 TRACE dnsdb_updater_www   File "/usr/local/open-dnsdb/dns_updater/app.py", line 21, in create_app
2019-01-23 15:08:28.217 16864 TRACE dnsdb_updater_www     setup_config(sys.argv[1], 'dnsdb-updater', conf_dir=os.path.dirname(os.path.dirname(__file__)))
2019-01-23 15:08:28.217 16864 TRACE dnsdb_updater_www   File "/usr/local/open-dnsdb/dns_updater/config.py", line 140, in setup_config
2019-01-23 15:08:28.217 16864 TRACE dnsdb_updater_www     CONF.host_group = DnsdbApi.get_host_group()['data']
2019-01-23 15:08:28.217 16864 TRACE dnsdb_updater_www   File "/usr/local/open-dnsdb/dns_updater/utils/updater_util.py", line 73, in get_host_group
2019-01-23 15:08:28.217 16864 TRACE dnsdb_updater_www     data={"host_ip": get_self_ip()})
2019-01-23 15:08:28.217 16864 TRACE dnsdb_updater_www   File "/usr/local/open-dnsdb/dnsdb_common/library/api.py", line 64, in get_form
2019-01-23 15:08:28.217 16864 TRACE dnsdb_updater_www     return self._get(url, *args, **dict(kwargs, **{'ctype': 'form'}))
2019-01-23 15:08:28.217 16864 TRACE dnsdb_updater_www   File "/usr/local/open-dnsdb/dnsdb_common/library/api.py", line 45, in _get
2019-01-23 15:08:28.217 16864 TRACE dnsdb_updater_www     return self.resp_wrapper(resp, req)
2019-01-23 15:08:28.217 16864 TRACE dnsdb_updater_www   File "/usr/local/open-dnsdb/dns_updater/utils/updater_util.py", line 59, in _dnsdb_resp_wrapper
2019-01-23 15:08:28.217 16864 TRACE dnsdb_updater_www     raise UpdaterErr(u'DnsdbApi调用失败: %s' % json.dumps(resp), 400, json.dumps(resp))
2019-01-23 15:08:28.217 16864 TRACE dnsdb_updater_www UpdaterErr: DnsdbApi调用失败: {"message": "\u8bf7\u5148\u5c06ip 192.168.41.51 \u5199\u5165\u6570\u636e\u5e93", "data": null, "errcode": 400, "msg_en": "No such ip record: 192.168.41.51"}
2019-01-23 15:08:28.217 16864 TRACE dnsdb_updater_www 

这是 dnsdb-updater.conf 的配置
 cat etc/beta/dnsdb-updater.conf
[etc]
tmp_dir=/usr/local/open-dnsdb/tmp
log_dir = /var/log/open-dnsdb
backup_dir=/usr/local/backup
pidfile=/usr/local/open-dnsdb/tmp/named_updater.pid
zone_update_interval = 5
allow_ip = 127.0.0.1

[log]
log-file = dnsdb_updater.log

[web]
port = 9000

[gunicorn]
bind = 0.0.0.0:9000

[bind_default]
named_dir = /etc
zone_dir = /var/named
acl_dir = /var/named
named_checkconf = /usr/sbin/named-checkconf
named_zonecheck = /usr/sbin/named-checkzone
mkrdns = /sbin/mkrdns
rndc = /usr/sbin/rndc

**Comment by LostSymbol** [comment]
![image](https://user-images.githubusercontent.com/24261160/51596393-d3e05b80-1f33-11e9-819a-2296dcf87a90.png)

需要在这个页面配置下主机, updater一般部署在bind服务器上

**Comment by shiweijie** [comment]
> ![image](https://user-images.githubusercontent.com/24261160/51596393-d3e05b80-1f33-11e9-819a-2296dcf87a90.png)
> 
> 需要在这个页面配置下主机, updater一般部署在bind服务器上

您好，主机已经添加， 会自动发现bind配置吗？？ 编辑配置 显示灰色   
![image](https://user-images.githubusercontent.com/20718492/51719943-685ad300-2086-11e9-995e-61c586b9adcb.png)
![image](https://user-images.githubusercontent.com/20718492/51719954-77da1c00-2086-11e9-9089-0bc7df6ca59d.png)
![image](https://user-images.githubusercontent.com/20718492/51720456-b375e580-2088-11e9-8eac-89de9fbc863b.png)

zone-updater 报错 
 /usr/local/open-dnsdb/tools/with_venv.sh dnsdb-zone-updater beta dnsdb-updater
192.168.41.51
2019-01-25 09:45:44.519 13751 ERROR dns_updater.updater [-] Host belong to group: WanMaster
2019-01-25 09:45:44.523 13751 CRITICAL dnsdb-zone-updater [-] u'WanMaster'
2019-01-25 09:45:44.523 13751 TRACE dnsdb-zone-updater Traceback (most recent call last):
2019-01-25 09:45:44.523 13751 TRACE dnsdb-zone-updater   File "/usr/local/open-dnsdb/.venv/bin/dnsdb-zone-updater", line 10, in <module>
2019-01-25 09:45:44.523 13751 TRACE dnsdb-zone-updater     sys.exit(updater())
2019-01-25 09:45:44.523 13751 TRACE dnsdb-zone-updater   File "/usr/local/open-dnsdb/dns_updater/utils/tool_classes.py", line 64, in wrap
2019-01-25 09:45:44.523 13751 TRACE dnsdb-zone-updater     self.run()
2019-01-25 09:45:44.523 13751 TRACE dnsdb-zone-updater   File "/usr/local/open-dnsdb/dns_updater/utils/tool_classes.py", line 58, in run
2019-01-25 09:45:44.523 13751 TRACE dnsdb-zone-updater     self.main_loop()
2019-01-25 09:45:44.523 13751 TRACE dnsdb-zone-updater   File "/usr/local/open-dnsdb/dns_updater/updater.py", line 101, in main_loop
2019-01-25 09:45:44.523 13751 TRACE dnsdb-zone-updater     class Worker(GenericWorker):
2019-01-25 09:45:44.523 13751 TRACE dnsdb-zone-updater   File "/usr/local/open-dnsdb/dns_updater/updater.py", line 102, in Worker
2019-01-25 09:45:44.523 13751 TRACE dnsdb-zone-updater     handler = _get_handler()
2019-01-25 09:45:44.523 13751 TRACE dnsdb-zone-updater   File "/usr/local/open-dnsdb/dns_updater/updater.py", line 32, in _get_handler
2019-01-25 09:45:44.523 13751 TRACE dnsdb-zone-updater     module = importlib.import_module(mapping[zone_group])
2019-01-25 09:45:44.523 13751 TRACE dnsdb-zone-updater KeyError: u'WanMaster'
2019-01-25 09:45:44.523 13751 TRACE dnsdb-zone-updater

**Comment by LostSymbol** [comment]
named.conf是需要手动导入的
简单的相关说明文档:
    https://github.com/qunarcorp/open_dnsdb/wiki/startUpdater
另外: 请更新下代码～

**Comment by shiweijie** [comment]
> named.conf是需要手动导入的
> 简单的相关说明文档:
> https://github.com/qunarcorp/open_dnsdb/wiki/startUpdater
> 另外: 请更新下代码～


感谢~~  
1.  flask import-named-conf --group_name Master --file_path /usr/local/named/etc/named.conf  #正常导入
2.  flask import-zone-records --zone_dir /var/named --zone_group Master --user test  #正常导入  --zone_group 的名字 就是 --group_name 名 吧 ？

3.
supervisor> reload
Really restart the remote supervisord process y/N? y
Restarted supervisord
supervisor> 
supervisor> status
open-dnsdb                       RUNNING   pid 27182, uptime 0:00:09
open-dnsdb-conf-updater          RUNNING   pid 27214, uptime 0:00:08
open-dnsdb-zone-updater          RUNNING   pid 27241, uptime 0:00:07
supervisor> 
supervisor> tail open-dnsdb-zone-updater
ACE dnsdb_upater_zone     return request('get', url, params=params, **kwargs)
2019-01-29 17:47:27.923 27213 TRACE dnsdb_upater_zone   File "/usr/local/open_dnsdb/.venv/lib/python2.7/site-packages/requests/api.py", line 60, in request
2019-01-29 17:47:27.923 27213 TRACE dnsdb_upater_zone     return session.request(method=method, url=url, **kwargs)
2019-01-29 17:47:27.923 27213 TRACE dnsdb_upater_zone   File "/usr/local/open_dnsdb/.venv/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
2019-01-29 17:47:27.923 27213 TRACE dnsdb_upater_zone     resp = self.send(prep, **send_kwargs)
2019-01-29 17:47:27.923 27213 TRACE dnsdb_upater_zone   File "/usr/local/open_dnsdb/.venv/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
2019-01-29 17:47:27.923 27213 TRACE dnsdb_upater_zone     r = adapter.send(request, **kwargs)
2019-01-29 17:47:27.923 27213 TRACE dnsdb_upater_zone   File "/usr/local/open_dnsdb/.venv/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
2019-01-29 17:47:27.923 27213 TRACE dnsdb_upater_zone     raise ConnectionError(e, request=request)
2019-01-29 17:47:27.923 27213 TRACE dnsdb_upater_zone ConnectionError: HTTPConnectionPool(host='localhost', port=9001): Max retries exceeded with url: /api/get/host_group (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f51cac05cd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-01-29 17:47:27.923 27213 TRACE dnsdb_upater_zone 
2019-01-29 17:47:29.228 27247 ERROR dns_updater.updater [-] Host belong to group: Master
##############################################################################

在更新zone的时候，提示连接不上 host 9001端口， 但是前两个服务都正常启动了 端口 9000和9001也是开的
![image](https://user-images.githubusercontent.com/20718492/51899797-ba855680-23ee-11e9-916e-fe50778b6d55.png)

![image](https://user-images.githubusercontent.com/20718492/51900735-fd482e00-23f0-11e9-89ce-7115949db588.png)

![image](https://user-images.githubusercontent.com/20718492/51900795-1f41b080-23f1-11e9-8943-6341df21f0d7.png)

![image](https://user-images.githubusercontent.com/20718492/51901158-fa017200-23f1-11e9-96e5-672c26448f5d.png)
