### ISSUE TITLE
添加解析不生效

### ISSUE THREAD

**Issue by diboca** [qunarcorp/open_dnsdb#39]
添加解析不生效，求指点······添加域名后/usr/local/open_dnsdb/tmp/var/named/*.zone 不能同步 /var/named下的*.zone文件，
5pu05paw5paH5Lu25aSx6LSlCuS4u+acujogc3ktNzUKLCDnsbvlnos6IG5hbWVkLmNvbmYsIOWO
n+WboDogcmVsb2FkIG5hbWVkLmNvbmYgZmFpbGVkOiBybmRjOiBjb25uZWN0aW9uIHRvIHJlbW90
ZSBob3N0IGNsb3NlZApUaGlzIG1heSBpbmRpY2F0ZSB0aGF0CiogdGhlIHJlbW90ZSBzZXJ2ZXIg
aXMgdXNpbmcgYW4gb2xkZXIgdmVyc2lvbiBvZiB0aGUgY29tbWFuZCBwcm90b2NvbCwKKiB0aGlz
IGhvc3QgaXMgbm90IGF1dGhvcml6ZWQgdG8gY29ubmVjdCwKKiB0aGUgY2xvY2tzIGFyZSBub3Qg
c3luY2hyb25pemVkLCBvcgoqIHRoZSBrZXkgaXMgaW52YWxpZC4=
, because: [Errno 110] Connection timed out
reload named.conf failed: rndc: connection to remote host closed
This may indicate that
* the remote server is using an older version of the command protocol,
* this host is not authorized to connect,
* the clocks are not synchronized, or
* the key is invalid.
2019-10-09 01:41:24.861 10818 TRACE dns_updater.api.worker Traceback (most recent call last):
2019-10-09 01:41:24.861 10818 TRACE dns_updater.api.worker   File "/usr/local/open_dnsdb/dns_updater/api/worker.py", line 204, in run
2019-10-09 01:41:24.861 10818 TRACE dns_updater.api.worker     self.update_named()
2019-10-09 01:41:24.861 10818 TRACE dns_updater.api.worker   File "/usr/local/open_dnsdb/dns_updater/api/worker.py", line 146, in update_named
2019-10-09 01:41:24.861 10818 TRACE dns_updater.api.worker     update_named_conf(self.group_name)
2019-10-09 01:41:24.861 10818 TRACE dns_updater.api.worker   File "/usr/local/open_dnsdb/dns_updater/api/worker.py", line 132, in update_named_conf
2019-10-09 01:41:24.861 10818 TRACE dns_updater.api.worker     reload_conf()
2019-10-09 01:41:24.861 10818 TRACE dns_updater.api.worker   File "/usr/local/open_dnsdb/dns_updater/api/worker.py", line 104, in reload_conf
2019-10-09 01:41:24.861 10818 TRACE dns_updater.api.worker     raise UpdaterErr('reload named.conf failed: %s' % output)
2019-10-09 01:41:24.861 10818 TRACE dns_updater.api.worker dnsdb_common.library.exception.UpdaterErr: reload named.conf failed: rndc: connection to remote host closed
2019-10-09 01:41:24.861 10818 TRACE dns_updater.api.worker This may indicate that
2019-10-09 01:41:24.861 10818 TRACE dns_updater.api.worker * the remote server is using an older version of the command protocol,
2019-10-09 01:41:24.861 10818 TRACE dns_updater.api.worker * this host is not authorized to connect,
2019-10-09 01:41:24.861 10818 TRACE dns_updater.api.worker * the clocks are not synchronized, or
2019-10-09 01:41:24.861 10818 TRACE dns_updater.api.worker * the key is invalid.
2019-10-09 01:41:24.861 10818 TRACE dns_updater.api.worker

**Comment by diboca** [comment]
> 求指点······
> ![1](https://user-images.githubusercontent.com/34181187/66405616-f6ac9480-ea1c-11e9-9617-48fd36fd8fa0.png)
> ![2](https://user-images.githubusercontent.com/34181187/66405628-fca27580-ea1c-11e9-84e3-6ce051a7565b.png)
> ![3](https://user-images.githubusercontent.com/34181187/66405638-0035fc80-ea1d-11e9-9170-81e2f1ed531b.png)
> ![4](https://user-images.githubusercontent.com/34181187/66405935-6ae73800-ea1d-11e9-9a24-1d51846a8822.png)
> ![5](https://user-images.githubusercontent.com/34181187/66405940-6b7fce80-ea1d-11e9-86f1-d9cf82089717.png)

**Comment by LostSymbol** [comment]
你的bind服务确定起来了么
这部分日志表明你的bind服务是有问题的：
reload named.conf failed: rndc: connection to remote host closed
This may indicate that

    the remote server is using an older version of the command protocol,
    this host is not authorized to connect,
    the clocks are not synchronized, or
    the key is invalid.
