### ISSUE TITLE
zone配置文件推送成功，但是host文件推送不成功。

### ISSUE THREAD

**Issue by 437049211** [qunarcorp/open_dnsdb#46]
**问题描述**
zone配置文件推送成功，但是host文件推送不成功。

**环境配置**
CentOS Linux release 7.4.1708 (Core) 
python3.6.8
bind-9.11.4
**复现步骤**
1.web页面配置域名和host。
2.查看系统推送文件。
[root@localhost open_dnsdb]# find / -name china.com
/var/named/chroot/var/named/china.com
/usr/local/open_dnsdb/tmp/var/named/china.com
[root@localhost open_dnsdb]# cat /var/named/chroot/var/named/china.com
$TTL 7200   ; 2 hours
@       IN SOA  localhost. root.localhost. (
            3000000000  ; Serial
            3600            ; Refresh (1 hour)
            900             ; Retry (15 minutes)
            3600000         ; Expire (5 weeks 6 days 16 hours)
            3600            ; Minimum (1 hour)
            )
@   2D  IN  NS  localhost.
$ORIGIN china.com.

[root@localhost open_dnsdb]# cat /usr/local/open_dnsdb/tmp/var/named/china.com
$TTL 7200   ; 2 hours
@       IN SOA  localhost. root.localhost. (
            3000000001  ; Serial
            3600            ; Refresh (1 hour)
            900             ; Retry (15 minutes)
            3600000         ; Expire (5 weeks 6 days 16 hours)
            3600            ; Minimum (1 hour)
            )
@   2D  IN  NS  localhost.
$ORIGIN china.com.

www      IN      A       10.0.0.1
3.

**实际输出结果**

**期望输出结果**
正常

**Comment by 437049211** [comment]
# 补充日志
[root@localhost open_dnsdb]# cat /var/log/open_dnsdb/mkrdns.log
(fatal) Can't open /usr/local/open_dnsdb/tmp/var/named/dynamic/china.com:No such file or directory at /sbin/mkrdns line 436.

**Comment by zengdd-pro** [comment]
你的安装成功了吗？
我环境是Python 3.8.5，安装都报错。
Requirement already up-to-date: pbr in ./.venv/lib/python3.8/site-packages (5.4.5)
Collecting concurrent-log-handler==0.9.12
  Using cached concurrent_log_handler-0.9.12-py2.py3-none-any.whl (41 kB)
Collecting Flask==1.0.2
  Using cached Flask-1.0.2-py2.py3-none-any.whl (91 kB)
Collecting Flask-Login==0.4.1
  Using cached Flask-Login-0.4.1.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/open_dnsdb-master/.venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w0ytt75c/flask-login/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w0ytt75c/flask-login/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-zzfwitol
         cwd: /tmp/pip-install-w0ytt75c/flask-login/
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/open_dnsdb-master/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 21, in <module>
        from setuptools.dist import Distribution
      File "/home/open_dnsdb-master/.venv/lib/python3.8/site-packages/_virtualenv.py", line 89, in exec_module
        old(module)
      File "/home/open_dnsdb-master/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 34, in <module>
        from setuptools import windows_support
      File "/home/open_dnsdb-master/.venv/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/usr/local/python3/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Command "tools/with_venv.sh pip install --upgrade -r /home/open_dnsdb-master/requirements.txt -r /home/open_dnsdb-master/test-requirements.txt" failed.
None
