### ISSUE TITLE
安装异常

### ISSUE THREAD

**Issue by zengdd-pro** [qunarcorp/open_dnsdb#49]
**问题描述**
Collecting Flask-Login==0.4.1
  Using cached Flask-Login-0.4.1.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/open_dnsdb-master/.venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w0ytt75c/flask-login/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w0ytt75c/flask-login/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-zzfwitol
         cwd: /tmp/pip-install-w0ytt75c/flask-login/
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/open_dnsdb-master/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 21, in <module>
        from setuptools.dist import Distribution
      File "/home/open_dnsdb-master/.venv/lib/python3.8/site-packages/_virtualenv.py", line 89, in exec_module
        old(module)
      File "/home/open_dnsdb-master/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 34, in <module>
        from setuptools import windows_support
      File "/home/open_dnsdb-master/.venv/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/usr/local/python3/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Command "tools/with_venv.sh pip install --upgrade -r /home/open_dnsdb-master/requirements.txt -r /home/open_dnsdb-master/test-requirements.txt" failed.
None

**环境配置**
Python 3.8.5

**复现步骤**
1.
2.
3.

**实际输出结果**

**期望输出结果**

**Comment by zengdd-pro** [comment]
ok
